"""
Django settings for djapp project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from os.path import abspath, dirname, basename, join, split

from local import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'gp=)qm!=2cfoeb&8z8gu*_f!vv1sjx%j%^m&4-82f4&f-v24@*'

# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djcelery',
    'chat',
    'ws',
    'django_sockjs_tornado',
    
)

SOCKJS_CLASSES = (
    'ws.server.ChatConnection',
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'djapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases



   


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = join(BASE_DIR, 'static')

TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
   )

SUIT_CONFIG = {
    'ADMIN_NAME': 'Angular Chat',

'MENU': (

        {'label': 'Apps', 'url': 'chat.tpa', 'icon':'icon-cog'},
        {'label': 'Users', 'url': 'chat.chatuser', 'icon':'icon-user'},
        
        {'label': 'Stop words', 'url': 'chat.chatstopword', 'icon':'icon-alert'},
        {'label': 'Templates', 'url': 'chat.chattemplates', 'icon':'icon-menu-hamburger'},
        {'label': 'Transactions', 'url': 'chat.chattransactions', 'icon':'icon-alert'},

        
       
    )
}

REDIS_HOST = "localhost"
REDIS_PORT = 6379

BROKER_URL = "redis://" + REDIS_HOST + "/0"
CELERYBEAT_SCHEDULER='djcelery.schedulers.DatabaseScheduler'


from datetime import timedelta
import djcelery
djcelery.setup_loader()
from celery.schedules import crontab
    
CELERYBEAT_SCHEDULE = {

    'charge-money': {
        'task': 'chat.tasks.charge_money',
        'schedule': timedelta(seconds=60)
    },

}











